buildscript {
    repositories {
        google()  // Google's Maven repository
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.5.2'
        classpath 'com.google.gms:google-services:4.4.2'
    }
}
allprojects {
    repositories {
        google()  // Google's Maven repository
        jcenter()
    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}
